import { Account } from "@/utils/types";

export const mockAccounts: Account[] = [
  {
    account_id: "ACC001",
    holder: {
      firstName: "Andrew",
      lastName: "McNulty",
      mobileNumber: "+1-224-463-7589",
      nickName: "jford",
      email: "a*@gmail.com",
      jointNames: "",
      username: "sample1",
      password: "sample1",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 115678.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "June 10 2024, 3:32:32 am",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 58000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "April 15 2023, 1:04:02 pm",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "February 8 2022, 10:11:22 am",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN004",
        dateTime: "July 2 2021, 7:08:32 am",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN005",
        dateTime: "November 23 2020, 1:15:02 pm",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN006",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN008",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN009",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN010",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN011",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN013",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN014",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN016",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN017",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
    ],
  },
  {
    account_id: "ACC002",
    holder: {
      firstName: "Jakob",
      lastName: "Maas",
      mobileNumber: "+1-224-463-7589",
      nickName: "jMas",
      gender: "Male",
      email: "j*@gmail.com",
      jointNames: "",
      username: "Jakobmaas",
      password: "Successful101",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 7200000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "June 10 2024, 3:32:32 am",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 58000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "April 15 2023, 1:04:02 pm",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "February 8 2022, 10:11:22 am",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN004",
        dateTime: "July 2 2021, 7:08:32 am",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN005",
        dateTime: "November 23 2020, 1:15:02 pm",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN006",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN008",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN009",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN010",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN011",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN013",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN014",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN016",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN017",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
    ],
  },
  {
    account_id: "ACC003",
    holder: {
      firstName: "Lanie",
      lastName: "Gardner",
      email: "l*@gmail.com",
      jointNames: "",
      username: "LanieGardner",
      password: "lanie6h3",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 250000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "July 22 2024, 2:03:08 am",
        description: "Transfer to Ashley Gardner",
        status: "Success",
        amount_usd: -20000.0,
        account_no: "****5001",
      },
      {
        transaction_id: "TXN002",
        dateTime: "February 14, 2024, 11:45:00 am",
        description: "Transfer from DEF Holdings",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****7632",
      },
      {
        transaction_id: "TXN003",
        dateTime: "January 5, 2024, 3:30:00 pm",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 2000.0,
        account_no: "****1928",
      },
      {
        transaction_id: "TXN004",
        dateTime: "April 20, 2023, 2:15:00 pm",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 15000.0,
        account_no: "****9485",
      },
      {
        transaction_id: "TXN005",
        dateTime: "February 18, 2023, 9:50:00 am",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 6500.0,
        account_no: "****1829",
      },
      {
        transaction_id: "TXN006",
        dateTime: "January 11, 2023, 1:40:00 pm",
        description: "Transfer from PQR Holdings",
        status: "Success",
        amount_usd: 18300.0,
        account_no: "****2753",
      },
      {
        transaction_id: "TXN007",
        dateTime: "May 14, 2022, 11:30:00 am",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -15000.0,
        account_no: "****3847",
      },
      {
        transaction_id: "TXN008",
        dateTime: "March 20, 2022, 4:25:00 pm",
        description: "Transfer to Amphenol",
        status: "Success",
        amount_usd: -17500.0,
        account_no: "****5729",
      },
      {
        transaction_id: "TXN009",
        dateTime: "January 9, 2022, 9:15:00 am",
        description: "Transfer from Cognizant Tech.",
        status: "Success",
        amount_usd: 2400.0,
        account_no: "****6437",
      },
      {
        transaction_id: "TXN010",
        dateTime: "June 22, 2021, 10:00:00 am",
        description: "Transfer from Danaher",
        status: "Success",
        amount_usd: 5340.0,
        account_no: "****8192",
      },
      {
        transaction_id: "TXN011",
        dateTime: "April 17, 2021, 3:20:00 pm",
        description: "Transfer from Kyndryl Holdings",
        status: "Success",
        amount_usd: 1200.0,
        account_no: "****3427",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 5, 2021, 1:55:00 pm",
        description: "Transfer from Amphenol",
        status: "Success",
        amount_usd: 22000.0,
        account_no: "****4628",
      },
      {
        transaction_id: "TXN013",
        dateTime: "August 20, 2020, 11:45:00 am",
        description: "Transfer from Aramark",
        status: "Success",
        amount_usd: 2100.0,
        account_no: "****1382",
      },
      {
        transaction_id: "TXN014",
        dateTime: "June 15, 2020, 10:10:00 am",
        description: "Transfer from Bella",
        status: "Success",
        amount_usd: 100.0,
        account_no: "****5724",
      },
      {
        transaction_id: "TXN015",
        dateTime: "April 5, 2020, 3:40:00 pm",
        description: "Transfer to Aramark",
        status: "Success",
        amount_usd: -50000.0,
        account_no: "****1963",
      },
      {
        transaction_id: "TXN016",
        dateTime: "October 14, 2019, 11:25:00 am",
        description: "Transfer to Bill Payment",
        status: "Success",
        amount_usd: -500.0,
        account_no: "****7584",
      },
      {
        transaction_id: "TXN017",
        dateTime: "August 22, 2019, 2:00:00 pm",
        description: "Transfer to Darden Restaurants",
        status: "Success",
        amount_usd: 800.0,
        account_no: "****2738",
      },
      {
        transaction_id: "TXN018",
        dateTime: "June 8, 2019, 4:35:00 pm",
        description: "Transfer from Danaher",
        status: "Success",
        amount_usd: 15300.0,
        account_no: "****1827",
      },
      {
        transaction_id: "TXN019",
        dateTime: "December 12, 2018, 10:50:00 am",
        description: "Transfer to Emerson Electric",
        status: "Success",
        amount_usd: 15000.0,
        account_no: "****5827",
      },
      {
        transaction_id: "TXN020",
        dateTime: "September 20, 2018, 3:15:00 pm",
        description: "Transfer from Kyndryl Holdings",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****3281",
      },
      {
        transaction_id: "TXN021",
        dateTime: "July 9, 2018, 1:30:00 pm",
        description: "Transfer from Marsh McLennan",
        status: "Success",
        amount_usd: 22000.0,
        account_no: "****2638",
      },
    ],
  },
  {
    account_id: "ACC004",
    holder: {
      firstName: "Jacob Smith",
      lastName: "",
      email: "j*@gmail.com",
      jointNames: "",
      username: "Smith's",
      password: "Iremide123",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 850000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN003",
        dateTime: "January 5, 2024, 3:30:00 pm",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 2000.0,
        account_no: "****1928",
      },
      {
        transaction_id: "TXN004",
        dateTime: "April 20, 2023, 2:15:00 pm",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 15000.0,
        account_no: "****9485",
      },
      {
        transaction_id: "TXN005",
        dateTime: "February 18, 2023, 9:50:00 am",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 6500.0,
        account_no: "****1829",
      },
      {
        transaction_id: "TXN006",
        dateTime: "January 11, 2023, 1:40:00 pm",
        description: "Transfer from PQR Holdings",
        status: "Success",
        amount_usd: 18300.0,
        account_no: "****2753",
      },
      {
        transaction_id: "TXN007",
        dateTime: "May 14, 2022, 11:30:00 am",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -15000.0,
        account_no: "****3847",
      },
      {
        transaction_id: "TXN008",
        dateTime: "March 20, 2022, 4:25:00 pm",
        description: "Transfer to Amphenol",
        status: "Success",
        amount_usd: -17500.0,
        account_no: "****5729",
      },
      {
        transaction_id: "TXN009",
        dateTime: "January 9, 2022, 9:15:00 am",
        description: "Transfer from Cognizant Tech.",
        status: "Success",
        amount_usd: 2400.0,
        account_no: "****6437",
      },
      {
        transaction_id: "TXN010",
        dateTime: "June 22, 2021, 10:00:00 am",
        description: "Transfer from Danaher",
        status: "Success",
        amount_usd: 5340.0,
        account_no: "****8192",
      },
      {
        transaction_id: "TXN011",
        dateTime: "April 17, 2021, 3:20:00 pm",
        description: "Transfer from Kyndryl Holdings",
        status: "Success",
        amount_usd: 1200.0,
        account_no: "****3427",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 5, 2021, 1:55:00 pm",
        description: "Transfer from Amphenol",
        status: "Success",
        amount_usd: 22000.0,
        account_no: "****4628",
      },
      {
        transaction_id: "TXN013",
        dateTime: "August 20, 2020, 11:45:00 am",
        description: "Transfer from Aramark",
        status: "Success",
        amount_usd: 2100.0,
        account_no: "****1382",
      },
      {
        transaction_id: "TXN014",
        dateTime: "June 15, 2020, 10:10:00 am",
        description: "Transfer from Bella",
        status: "Success",
        amount_usd: 100.0,
        account_no: "****5724",
      },
      {
        transaction_id: "TXN015",
        dateTime: "April 5, 2020, 3:40:00 pm",
        description: "Transfer to Aramark",
        status: "Success",
        amount_usd: -50000.0,
        account_no: "****1963",
      },
      {
        transaction_id: "TXN016",
        dateTime: "October 14, 2019, 11:25:00 am",
        description: "Transfer to Bill Payment",
        status: "Success",
        amount_usd: -500.0,
        account_no: "****7584",
      },
      {
        transaction_id: "TXN017",
        dateTime: "August 22, 2019, 2:00:00 pm",
        description: "Transfer to Darden Restaurants",
        status: "Success",
        amount_usd: 800.0,
        account_no: "****2738",
      },
      {
        transaction_id: "TXN018",
        dateTime: "June 8, 2019, 4:35:00 pm",
        description: "Transfer from Danaher",
        status: "Success",
        amount_usd: 15300.0,
        account_no: "****1827",
      },
      {
        transaction_id: "TXN019",
        dateTime: "December 12, 2018, 10:50:00 am",
        description: "Transfer to Emerson Electric",
        status: "Success",
        amount_usd: 15000.0,
        account_no: "****5827",
      },
      {
        transaction_id: "TXN020",
        dateTime: "September 20, 2018, 3:15:00 pm",
        description: "Transfer from Kyndryl Holdings",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****3281",
      },
      {
        transaction_id: "TXN021",
        dateTime: "July 9, 2018, 1:30:00 pm",
        description: "Transfer from Marsh McLennan",
        status: "Success",
        amount_usd: 22000.0,
        account_no: "****2638",
      },
    ],
  },
  {
    account_id: "ACC005",
    holder: {
      firstName: "Richard",
      lastName: "Storm",
      email: "r*@gmail.com",
      jointNames: "",
      username: "MargretBartfield",
      password: "Richie98$5",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 1000000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "July 10 2024, 3:32:32 am",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 58000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "April 15 2024, 1:04:02 pm",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "February 8 2024, 10:11:22 am",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN004",
        dateTime: "July 2 2023, 7:08:32 am",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN005",
        dateTime: "May 23 2023, 1:15:02 pm",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN006",
        dateTime: "April 23 2022, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "March 15, 2022, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN008",
        dateTime: "February 12, 2022, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN009",
        dateTime: "November 16, 2021, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN010",
        dateTime: "October 23 2021, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN011",
        dateTime: "March 15, 2021, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "May 12, 2020, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN013",
        dateTime: "April 16, 2020, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN014",
        dateTime: "August 23 2019, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN016",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC006",
    holder: {
      firstName: "Roland",
      lastName: "Nashoba",
      email: "rolandnashoba@gmail.com",
      jointNames: "",
      username: "rolandnashoba",
      password: "Nashoba090@",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 928000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "September 13 2017, 3:32:32 pm",
        description: "Magnolia Oil & Gas Corporation",
        status: "Success",
        amount_usd: 862700.0,
        account_no: "****5009",
      },

      {
        transaction_id: "TXN002",
        dateTime: "March 13 2017, 1:04:02 pm",
        description: "Celeb City Farms",
        status: "Success",
        amount_usd: 16000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "October 27 2016, 11:00:12 am",
        description: "Brunt Work Wear and Maintenance Service",
        status: "Success",
        amount_usd: -1000.0,
        account_no: "****5242",
      },
      {
        transaction_id: "TXN004",
        dateTime: "April 15 2015, 11:00:12 am",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 100.0,
        account_no: "****1436",
      },
      {
        transaction_id: "TXN005",
        dateTime: "April 3 2015, 4:22:03 pm",
        description: "Department Workers",
        status: "Success",
        amount_usd: -15000.0,
        account_no: "****9422",
      },
      {
        transaction_id: "TXN005",
        dateTime: "January 15 2015, 1:04:02 pm",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 100.0,
        account_no: "****0038",
      },
      {
        transaction_id: "TXN006",
        dateTime: "January 8 2014, 10:11:22 am",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 2100.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN007",
        dateTime: "July 2 2013, 7:08:32 am",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 15000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN008",
        dateTime: "May 23 2013, 1:15:02 pm",
        description: "Transfer from BT Group",
        status: "Success",
        amount_usd: 49000.0,
        account_no: "****1403",
      },
    ],
  },
  {
    account_id: "ACC007",
    holder: {
      firstName: "Ailbert Stan",
      lastName: "",
      email: "loganstan1111@gmail.com",
      jointNames: "",
      username: "loganstan1111",
      password: "Ailbertmackyla$1111",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 3670890.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "September 15 2024",
        description: "Transfer from Ailbert Mackyla",
        status: "Success",
        amount_usd: 30000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "August 18 2024",
        description: "Walmart",
        status: "Success",
        amount_usd: -250.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "August 1 2024",
        description: "Withdrawal",
        status: "Success",
        amount_usd: -1250.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "April 15 2024",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "February 8 2024",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "July 2 2023",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "May 23 2023",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "April 23 2022",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 7500.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "March 15, 2022",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 28300.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "February 12, 2022",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN011",
        dateTime: "November 16, 2021",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN012",
        dateTime: "October 23 2021",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN013",
        dateTime: "March 15, 2021",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN014",
        dateTime: "May 12, 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN015",
        dateTime: "April 16, 2020",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN016",
        dateTime: "August 23 2019",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN017",
        dateTime: "March 15, 2019",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN018",
        dateTime: "February 12, 2019",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC008",
    holder: {
      firstName: "Hannna",
      lastName: "Rothrock",
      email: "h@gmail.com",
      jointNames: "",
      username: "hannnarothrock1",
      password: "qjVByh4PDAs8",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 2000000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "September 15 2024",
        description: "Transfer from Ailbert Mackyla",
        status: "Success",
        amount_usd: 30000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "August 18 2024",
        description: "Walmart",
        status: "Success",
        amount_usd: -250.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "August 1 2024",
        description: "Withdrawal",
        status: "Success",
        amount_usd: -1250.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "April 15 2024",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "February 8 2024",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "July 2 2023",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "May 23 2023",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "April 23 2022",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 7500.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "March 15, 2022",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 28300.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "February 12, 2022",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN011",
        dateTime: "November 16, 2021",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN012",
        dateTime: "October 23 2021",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN013",
        dateTime: "March 15, 2021",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN014",
        dateTime: "May 12, 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN015",
        dateTime: "April 16, 2020",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN016",
        dateTime: "August 23 2019",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN017",
        dateTime: "March 15, 2019",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN018",
        dateTime: "February 12, 2019",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC009",
    holder: {
      firstName: "Christopher Bright C.",
      lastName: "",
      email: "c@gmail.com",
      jointNames: "",
      username: "Christopher1979",
      password: "Bella@1979",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 760870.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "July 6 2023, 3:00:02pm",
        description: "Celeb City Farms ",
        status: "Success",
        amount_usd: 4000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "January 10 2023, 5:15:02pm",
        description: "Company Officials",
        status: "Success",
        amount_usd: -15750.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "December 5 2022, 8:30:08am",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 3100.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 19 2022, 1:03:05pm",
        description: "Company Van Maintenance ",
        status: "Success",
        amount_usd: -1500.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "September 13 2021, 2:10:06pm",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "June 24 2021, 9:00:13am",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "February 3 2020, 4:22:05pm",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "January 8 2020, 10:11:22am",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 20 2019, 2:00pm",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 23 2019, 8:50am",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC010",
    holder: {
      firstName: "Vannesa",
      lastName: "Alex",
      email: "v@gmail.com",
      jointNames: "",
      username: "Venessa1979",
      password: "Daughter001",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 2160737.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "October 1 2024",
        description: "Transfer to Charity Home Ca. ",
        status: "Success",
        amount_usd: -5000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "September 15 2024",
        description: "Celeb City Farms ",
        status: "Success",
        amount_usd: 4000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "September 10 2024",
        description: "Company Officials",
        status: "Success",
        amount_usd: -15750.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "December 5 2023",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 3100.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 19 2023",
        description: "Company Van Maintenance ",
        status: "Success",
        amount_usd: -1500.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "September 13 2022",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "June 24 2022",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "February 3 2021",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "January 8 2021",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 20 2020",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 23 2020",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC011",
    holder: {
      firstName: "Connie",
      lastName: "Curran",
      email: "c@gmail.com",
      jointNames: "",
      username: "Curran1854",
      password: "Curran12@",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 1128000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "October 1 2024",
        description: "Housing Payment",
        status: "Success",
        amount_usd: 550000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "September 23 2024",
        description: "Car Payment",
        status: "Success",
        amount_usd: 120000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "September 10 2024",
        description: "Antique Materials",
        status: "Success",
        amount_usd: 85000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "August 18 2024",
        description: "Land Payment",
        status: "Success",
        amount_usd: 780000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 19 2023",
        description: "Company Van Maintenance ",
        status: "Success",
        amount_usd: -1500.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "September 13 2022",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "June 24 2022",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "February 3 2021",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "January 8 2021",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 20 2020",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 23 2020",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC012",
    holder: {
      firstName: "Cooper",
      lastName: "Alan",
      email: "c@gmail.com",
      jointNames: "",
      username: "cooper123",
      password: "Timalan12$",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 500000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "October 1 2024",
        description: "Housing Payment",
        status: "Success",
        amount_usd: 5500.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "September 23 2024",
        description: "Car Payment",
        status: "Success",
        amount_usd: 1200.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "September 10 2024",
        description: "Antique Materials",
        status: "Success",
        amount_usd: 8500.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "August 18 2024",
        description: "Land Payment",
        status: "Success",
        amount_usd: 7800.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 19 2023",
        description: "Company Van Maintenance ",
        status: "Success",
        amount_usd: -1500.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "September 13 2022",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "June 24 2022",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "February 3 2021",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "January 8 2021",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 20 2020",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 23 2020",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC013",
    holder: {
      firstName: "Richard",
      lastName: "Laure",
      email: "r@gmail.com",
      jointNames: "",
      username: "Richard109",
      password: "Chard@001",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 300000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "November 10 2024",
        description: "Transfer from Charity Home Ca. ",
        status: "Success",
        amount_usd: 5000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "September 15 2024",
        description: "Celeb City Farms ",
        status: "Success",
        amount_usd: 4000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "September 10 2024",
        description: "Company Officials",
        status: "Success",
        amount_usd: -15750.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "December 5 2023",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 3100.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 19 2023",
        description: "Company Van Maintenance ",
        status: "Success",
        amount_usd: -1500.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "September 13 2022",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "June 24 2022",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "February 3 2021",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "January 8 2021",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 20 2020",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 23 2020",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC014",
    holder: {
      firstName: "Troy W Robbinson",
      lastName: "",
      email: "t***@gmail.com",
      jointNames: "",
      username: "Weldertroy2019",
      password: "TroyRob2030",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 964587.2,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "September 23 2024, 8:50am",
        description: "DEPOSIT XXXXXX8324",
        status: "Success",
        amount_usd: 170000.0,
      },
      {
        transaction_id: "TXN002",
        dateTime: "September 5 2024, 1:03:05pm",
        description: "Wells Fargo CD profit XXXXXX8324",
        status: "Success",
        amount_usd: 41840.4,
      },
      {
        transaction_id: "TXN003",
        dateTime: "August 6 2024, 3:00:02pm",
        description: "Tfr from Fort Worth Welders Supply Inc XXXXXX8324",
        status: "Success",
        amount_usd: 98000.0,
      },
      {
        transaction_id: "TXN004",
        dateTime: "July 9 2024, 5:15:02pm",
        description: "Tfr from Forney Fence Supply XXXXXX8324",
        status: "Success",
        amount_usd: 47000.0,
      },
      {
        transaction_id: "TXN005",
        dateTime: "June 19 2024, 1:03:05pm",
        description: "Wells Fargo CD profit XXXXXX8324",
        status: "Success",
        amount_usd: 45840.4,
      },
      {
        transaction_id: "TXN006",
        dateTime: "May 13 2024, 2:10:06pm ",
        description: "Tfr from Lincoln Electrics XXXXXX8324 Funds Transfer",
        status: "Success",
        amount_usd: 45650.8,
      },
      {
        transaction_id: "TXN007",
        dateTime: "May 3 2024, 4:22:05pm",
        description: "Metroplex Welding Supply Inc ",
        status: "Success",
        amount_usd: -42450.5,
      },
      {
        transaction_id: "TXN008",
        dateTime: "April 8 2024, 10:11:22am",
        description: "Tfr from Lincoln Electrics XXXXXX2819",
        status: "Success",
        amount_usd: 65500.7,
      },
      {
        transaction_id: "TXN009",
        dateTime: "March 30 2024, 2:06pm",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -7500.5,
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 23 2024, 8:50am",
        description: "DEPOSIT XXXXXX8324",
        status: "Success",
        amount_usd: 450754.9,
      },
    ],
  },
  {
    account_id: "ACC015",
    holder: {
      firstName: "Wood Andra B.",
      lastName: "",
      email: "w***@gmail.com",
      dateCreated: "1/10/2025",
      username: "WoodbeckieRoddy!",
      password: "JasonwayneRoddy",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 760870.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        dateTime: "July 6 2023, 3:00:02pm",
        description: "Celeb City Farms",
        status: "Success",
        amount_usd: 4000.0,
      },
      {
        dateTime: "January 10 2023, 5:15:02pm",
        description: "Company Officials",
        status: "Success",
        amount_usd: -15750.0,
      },
      {
        dateTime: "December 5 2022, 8:30:08am",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 3100.0,
      },
      {
        dateTime: "October 19 2022, 1:03:05pm",
        description: "Company Van Maintenance",
        status: "Success",
        amount_usd: -1500.0,
      },
      {
        dateTime: "September 13 2021, 2:10:06pm",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
      },
      {
        dateTime: "June 24 2021, 9:00:13am",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
      },
      {
        dateTime: "February 3 2020, 4:22:05pm",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
      },
      {
        dateTime: "January 8 2020, 10:11:22am",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
      },
      {
        dateTime: "May 20 2019, 2:00pm",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
      },
      {
        dateTime: "March 23 2019, 8:50am",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
      },
      {
        dateTime: "August 23 2018, 8:50am",
        description: "Transfer to Nikky&co enterprises",
        status: "Success",
        amount_usd: -66500.0,
      },
      {
        dateTime: "March 23 2018, 8:50am",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 33200.0,
      },
      {
        dateTime: "November 15 2023, 12:45:00pm",
        description: "Office Supplies Purchase",
        status: "Success",
        amount_usd: -2300.0,
      },
      {
        dateTime: "April 9 2022, 11:30:45am",
        description: "Refund from Vendor",
        status: "Success",
        amount_usd: 1200.0,
      },
      {
        dateTime: "February 18 2021, 10:05:23am",
        description: "IT Equipment Maintenance",
        status: "Success",
        amount_usd: -7800.0,
      },
      {
        dateTime: "December 29 2020, 2:22:11pm",
        description: "Transfer to Company Savings",
        status: "Success",
        amount_usd: 5000.0,
      },
      {
        dateTime: "July 4 2019, 3:14:52pm",
        description: "Employee Travel Reimbursement",
        status: "Success",
        amount_usd: -4200.0,
      },
      {
        dateTime: "October 10 2018, 4:50:35pm",
        description: "Transfer from Parent Organization",
        status: "Success",
        amount_usd: 20000.0,
      },
    ],
  },
  {
    account_id: "ACC015",
    holder: {
      firstName: "James Mia M.",
      lastName: "",
      email: "j***@gmail.com",
      dateCreated: "1/11/2025",// m/d/y
      username: "jamesmia1",
      password: "Nou17053583$",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 965870.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        dateTime: "January 8 2025",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 15000.0,
      },
      {
        dateTime: "January 5 2025",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -500.0,
      },
      {
        dateTime: "October 1 2024",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 15000.0,
      },
      {
        dateTime: "September 23 2024",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 25000.0,
      },
      {
        dateTime: "September 10 2024",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 120000.0,
      },
      {
        dateTime: "August 18 2024",
        description: "Land Payment",
        status: "Success",
        amount_usd: 78000.0,
      },
      {
        dateTime: "July 6 2023, 3:00:02pm",
        description: "Celeb City Farms",
        status: "Success",
        amount_usd: 4000.0,
      },
      {
        dateTime: "January 10 2023, 5:15:02pm",
        description: "Company Officials",
        status: "Success",
        amount_usd: -15750.0,
      },
      {
        dateTime: "December 5 2022, 8:30:08am",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 3100.0,
      },
      {
        dateTime: "October 19 2022, 1:03:05pm",
        description: "Company Van Maintenance",
        status: "Success",
        amount_usd: -1500.0,
      },
      {
        dateTime: "September 13 2021, 2:10:06pm",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
      },
      {
        dateTime: "June 24 2021, 9:00:13am",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
      },
      {
        dateTime: "February 3 2020, 4:22:05pm",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
      },
      {
        dateTime: "January 8 2020, 10:11:22am",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
      },
      {
        dateTime: "May 20 2019, 2:00pm",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
      },
      {
        dateTime: "March 23 2019, 8:50am",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
      },
      {
        dateTime: "August 23 2018, 8:50am",
        description: "Transfer to Nikky&co enterprises",
        status: "Success",
        amount_usd: -66500.0,
      },
      {
        dateTime: "March 23 2018, 8:50am",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 33200.0,
      },
      {
        dateTime: "November 15 2023, 12:45:00pm",
        description: "Office Supplies Purchase",
        status: "Success",
        amount_usd: -2300.0,
      },
      {
        dateTime: "April 9 2022, 11:30:45am",
        description: "Refund from Vendor",
        status: "Success",
        amount_usd: 1200.0,
      },
      {
        dateTime: "February 18 2021, 10:05:23am",
        description: "IT Equipment Maintenance",
        status: "Success",
        amount_usd: -7800.0,
      },
      {
        dateTime: "December 29 2020, 2:22:11pm",
        description: "Transfer to Company Savings",
        status: "Success",
        amount_usd: 5000.0,
      },
      {
        dateTime: "July 4 2019, 3:14:52pm",
        description: "Employee Travel Reimbursement",
        status: "Success",
        amount_usd: -4200.0,
      },
      {
        dateTime: "October 10 2018, 4:50:35pm",
        description: "Transfer from Parent Organization",
        status: "Success",
        amount_usd: 20000.0,
      },
    ],
  },
  {
    account_id: "ACC016",
    holder: {
      firstName: "Sharon Ben Fechter",
      lastName: "",
      email: "s***@gmail.com",
      dateCreated: "1/24/2025",// m/d/y
      username: "Sharon4122",
      password: "Tomisthe14me",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 799350.71,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "237832",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        dateTime: "January 23 2025",
        description: "Transfer from Paris Event",
        status: "Success",
        amount_usd: 750000.0,
      },
      {
        dateTime: "January 20 2025",
        description: "PetroQuest Energy Payment",
        status: "Success",
        amount_usd: 11000.0,
      },
      {
        dateTime: "January 18 2025",
        description: "W&T Offshore Invoice",
        status: "Success",
        amount_usd: 8500.0,
      },
      {
        dateTime: "January 17 2025",
        description: "Comstock Resources Contract",
        status: "Success",
        amount_usd: 7500.0,
      },
      {
        dateTime: "January 15 2025",
        description: "Abraxas Petroleum Settlement",
        status: "Success",
        amount_usd: 6000.0,
      },
      {
        dateTime: "January 13 2025",
        description: "Northern Oil and Gas Royalty",
        status: "Success",
        amount_usd: 4500.0,
      },
      {
        dateTime: "January 12 2025",
        description: "Earthstone Energy Licensing",
        status: "Success",
        amount_usd: 2500.0,
      },
      {
        dateTime: "October 1 2024",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 15000.0,
      },
      {
        dateTime: "September 23 2024",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 25000.0,
      },
      {
        dateTime: "September 10 2024",
        description: "Transfer from Cory Mack",
        status: "Success",
        amount_usd: 120000.0,
      },
      {
        dateTime: "August 18 2024",
        description: "Land Payment",
        status: "Success",
        amount_usd: 78000.0,
      },
      {
        dateTime: "July 6 2023, 3:00:02pm",
        description: "Celeb City Farms",
        status: "Success",
        amount_usd: 4000.0,
      },
      {
        dateTime: "January 10 2023, 5:15:02pm",
        description: "Company Officials",
        status: "Success",
        amount_usd: -15750.0,
      },
      {
        dateTime: "December 5 2022, 8:30:08am",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 3100.0,
      },
      {
        dateTime: "October 19 2022, 1:03:05pm",
        description: "Company Van Maintenance",
        status: "Success",
        amount_usd: -1500.0,
      },
      {
        dateTime: "September 13 2021, 2:10:06pm",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 4500.0,
      },
      {
        dateTime: "June 24 2021, 9:00:13am",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
      },
      {
        dateTime: "February 3 2020, 4:22:05pm",
        description: "Department Workers",
        status: "Success",
        amount_usd: -10000.0,
      },
      {
        dateTime: "January 8 2020, 10:11:22am",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 7500.0,
      },
      {
        dateTime: "May 20 2019, 2:00pm",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
      },
      {
        dateTime: "March 23 2019, 8:50am",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
      },
      {
        dateTime: "August 23 2018, 8:50am",
        description: "Transfer to Nikky&co enterprises",
        status: "Success",
        amount_usd: -66500.0,
      },
      {
        dateTime: "March 23 2018, 8:50am",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 33200.0,
      },
      {
        dateTime: "November 15 2023, 12:45:00pm",
        description: "Office Supplies Purchase",
        status: "Success",
        amount_usd: -2300.0,
      },
      {
        dateTime: "April 9 2022, 11:30:45am",
        description: "Refund from Vendor",
        status: "Success",
        amount_usd: 1200.0,
      },
      {
        dateTime: "February 18 2021, 10:05:23am",
        description: "IT Equipment Maintenance",
        status: "Success",
        amount_usd: -7800.0,
      },
      {
        dateTime: "December 29 2020, 2:22:11pm",
        description: "Transfer to Company Savings",
        status: "Success",
        amount_usd: 5000.0,
      },
      {
        dateTime: "July 4 2019, 3:14:52pm",
        description: "Employee Travel Reimbursement",
        status: "Success",
        amount_usd: -4200.0,
      },
      {
        dateTime: "October 10 2018, 4:50:35pm",
        description: "Transfer from Parent Organization",
        status: "Success",
        amount_usd: 20000.0,
      },
    ],
  },
];
