import { Account } from "@/utils/types";

export const mockAccounts: Account[] = [
  {
    account_id: "ACC001",
    holder: {
      firstName: "Andrew",
      lastName: "McNulty",
      mobileNumber: "+1-224-463-7589",
      nickName: "jford",
      email: "a*@gmail.com",
      jointNames: "",
      username: "sample1",
      password: "sample1",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 115678.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "June 10 2024, 3:32:32 am",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 58000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "April 15 2023, 1:04:02 pm",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "February 8 2022, 10:11:22 am",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN004",
        dateTime: "July 2 2021, 7:08:32 am",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN005",
        dateTime: "November 23 2020, 1:15:02 pm",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN006",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN008",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN009",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN010",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN011",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN013",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN014",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN016",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN017",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
    ],
  },
  {
    account_id: "ACC002",
    holder: {
      firstName: "Jakob",
      lastName: "Maas",
      mobileNumber: "+1-224-463-7589",
      nickName: "jMas",
      gender: "Male",
      email: "j*@gmail.com",
      jointNames: "",
      username: "Jakobmaas",
      password: "Successful101",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 7200000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "June 10 2024, 3:32:32 am",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 58000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "April 15 2023, 1:04:02 pm",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "February 8 2022, 10:11:22 am",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN004",
        dateTime: "July 2 2021, 7:08:32 am",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN005",
        dateTime: "November 23 2020, 1:15:02 pm",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN006",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN008",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN009",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN010",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN011",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN013",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN014",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN016",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN017",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
    ],
  },
  {
    account_id: "ACC003",
    holder: {
      firstName: "Lanie",
      lastName: "Gardner",
      email: "l*@gmail.com",
      jointNames: "",
      username: "LanieGardner",
      password: "lanie6h3",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 250000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "July 29 2024, 2:03:08 am",
        description: "Transfer to Ashley Gardner",
        status: "Success",
        amount_usd: -20000.0,
        account_no: "****5001",
      },
      {
        transaction_id: "TXN002",
        dateTime: "February 14, 2024, 11:45:00 am",
        description: "Transfer from DEF Holdings",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****7632",
      },
      {
        transaction_id: "TXN003",
        dateTime: "January 5, 2024, 3:30:00 pm",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 2000.0,
        account_no: "****1928",
      },
      {
        transaction_id: "TXN004",
        dateTime: "April 20, 2023, 2:15:00 pm",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 15000.0,
        account_no: "****9485",
      },
      {
        transaction_id: "TXN005",
        dateTime: "February 18, 2023, 9:50:00 am",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 6500.0,
        account_no: "****1829",
      },
      {
        transaction_id: "TXN006",
        dateTime: "January 11, 2023, 1:40:00 pm",
        description: "Transfer from PQR Holdings",
        status: "Success",
        amount_usd: 18300.0,
        account_no: "****2753",
      },
      {
        transaction_id: "TXN007",
        dateTime: "May 14, 2022, 11:30:00 am",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -15000.0,
        account_no: "****3847",
      },
      {
        transaction_id: "TXN008",
        dateTime: "March 20, 2022, 4:25:00 pm",
        description: "Transfer to Amphenol",
        status: "Success",
        amount_usd: -17500.0,
        account_no: "****5729",
      },
      {
        transaction_id: "TXN009",
        dateTime: "January 9, 2022, 9:15:00 am",
        description: "Transfer from Cognizant Tech.",
        status: "Success",
        amount_usd: 2400.0,
        account_no: "****6437",
      },
      {
        transaction_id: "TXN010",
        dateTime: "June 22, 2021, 10:00:00 am",
        description: "Transfer from Danaher",
        status: "Success",
        amount_usd: 5340.0,
        account_no: "****8192",
      },
      {
        transaction_id: "TXN011",
        dateTime: "April 17, 2021, 3:20:00 pm",
        description: "Transfer from Kyndryl Holdings",
        status: "Success",
        amount_usd: 1200.0,
        account_no: "****3427",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 5, 2021, 1:55:00 pm",
        description: "Transfer from Amphenol",
        status: "Success",
        amount_usd: 22000.0,
        account_no: "****4628",
      },
      {
        transaction_id: "TXN013",
        dateTime: "August 20, 2020, 11:45:00 am",
        description: "Transfer from Aramark",
        status: "Success",
        amount_usd: 2100.0,
        account_no: "****1382",
      },
      {
        transaction_id: "TXN014",
        dateTime: "June 15, 2020, 10:10:00 am",
        description: "Transfer from Bella",
        status: "Success",
        amount_usd: 100.0,
        account_no: "****5724",
      },
      {
        transaction_id: "TXN015",
        dateTime: "April 5, 2020, 3:40:00 pm",
        description: "Transfer to Aramark",
        status: "Success",
        amount_usd: -50000.0,
        account_no: "****1963",
      },
      {
        transaction_id: "TXN016",
        dateTime: "October 14, 2019, 11:25:00 am",
        description: "Transfer to Bill Payment",
        status: "Success",
        amount_usd: -500.0,
        account_no: "****7584",
      },
      {
        transaction_id: "TXN017",
        dateTime: "August 22, 2019, 2:00:00 pm",
        description: "Transfer to Darden Restaurants",
        status: "Success",
        amount_usd: 800.0,
        account_no: "****2738",
      },
      {
        transaction_id: "TXN018",
        dateTime: "June 8, 2019, 4:35:00 pm",
        description: "Transfer from Danaher",
        status: "Success",
        amount_usd: 15300.0,
        account_no: "****1827",
      },
      {
        transaction_id: "TXN019",
        dateTime: "December 12, 2018, 10:50:00 am",
        description: "Transfer to Emerson Electric",
        status: "Success",
        amount_usd: 15000.0,
        account_no: "****5827",
      },
      {
        transaction_id: "TXN020",
        dateTime: "September 20, 2018, 3:15:00 pm",
        description: "Transfer from Kyndryl Holdings",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****3281",
      },
      {
        transaction_id: "TXN021",
        dateTime: "July 9, 2018, 1:30:00 pm",
        description: "Transfer from Marsh McLennan",
        status: "Success",
        amount_usd: 22000.0,
        account_no: "****2638",
      },
    ],
  },
];
